"""
Prosperity 4 - Algorithmic Trading Bot v1.0
Strategy: Mean-Reversion Market Maker

This bot implements a market-making strategy that:
1. Places bid/ask orders to capture the spread
2. Uses mean-reversion to adjust fair value estimates
3. Manages inventory risk with position limits
4. Dynamically adjusts quotes based on market conditions
"""

import csv
import glob
from collections import deque
from dataclasses import dataclass, field
from typing import Optional


# ============================================================
# Configuration
# ============================================================
@dataclass
class Config:
    # General settings
    DATA_DIR: str = "TUTORIAL_ROUND_1"
    
    # EMERALDS configuration
    EMERALDS_FAIR_VALUE: float = 10000.0
    EMERALDS_SPREAD_TARGET: float = 8.0  # Half-spread from fair value
    EMERALDS_ORDER_SIZE: int = 8
    EMERALDS_MAX_POSITION: int = 30
    
    # TOMATOES configuration
    TOMATOES_FAIR_VALUE: float = 5000.0
    TOMATOES_SPREAD_TARGET: float = 7.0  # Half-spread from fair value
    TOMATOES_ORDER_SIZE: int = 5
    TOMATOES_MAX_POSITION: int = 25
    
    # Mean reversion settings
    MA_WINDOW: int = 20  # Rolling mean window for mid-price
    
    # Inventory skew settings
    INVENTORY_SKEW_FACTOR: float = 0.5  # How much to skew quotes based on position
    
    # Volatility adjustment
    VOL_LOOKBACK: int = 10
    VOL_SPREAD_MULTIPLIER: float = 1.5


# ============================================================
# Data Structures
# ============================================================
@dataclass
class OrderBookLevel:
    """Represents a single order book snapshot for a product"""
    day: int
    timestamp: int
    product: str
    
    # Bid side (prices people are willing to BUY at)
    bid_price_1: Optional[float] = None
    bid_volume_1: Optional[int] = None
    bid_price_2: Optional[float] = None
    bid_volume_2: Optional[int] = None
    bid_price_3: Optional[float] = None
    bid_volume_3: Optional[int] = None
    
    # Ask side (prices people are willing to SELL at)
    ask_price_1: Optional[float] = None
    ask_volume_1: Optional[int] = None
    ask_price_2: Optional[float] = None
    ask_volume_2: Optional[int] = None
    ask_price_3: Optional[float] = None
    ask_volume_3: Optional[int] = None
    
    mid_price: Optional[float] = None


@dataclass
class Trade:
    """Represents an executed trade"""
    timestamp: int
    buyer: str
    seller: str
    symbol: str
    price: float
    quantity: int


@dataclass
class Position:
    """Tracks current position for a product"""
    symbol: str
    quantity: int = 0  # Positive = long, Negative = short
    avg_entry_price: float = 0.0
    realized_pnl: float = 0.0


@dataclass
class Signal:
    """Trading signal generated by the strategy"""
    symbol: str
    action: str  # "BUY", "SELL", "HOLD"
    price: float
    quantity: int
    confidence: float  # 0.0 to 1.0


# ============================================================
# Data Loading
# ============================================================
class DataLoader:
    """Loads and parses market data from CSV files"""
    
    def __init__(self, data_dir: str):
        self.data_dir = data_dir
    
    def load_prices(self) -> list[OrderBookLevel]:
        """Load all price data from CSV files"""
        prices = []

        # Find all price files
        price_files = glob.glob(self.data_dir + "/prices_*.csv")

        for filepath in sorted(price_files):
            with open(filepath, 'r') as f:
                reader = csv.DictReader(f, delimiter=';')
                for row in reader:
                    level = OrderBookLevel(
                        day=int(row['day']),
                        timestamp=int(row['timestamp']),
                        product=row['product'],
                        bid_price_1=self._safe_float(row.get('bid_price_1')),
                        bid_volume_1=self._safe_int(row.get('bid_volume_1')),
                        bid_price_2=self._safe_float(row.get('bid_price_2')),
                        bid_volume_2=self._safe_int(row.get('bid_volume_2')),
                        bid_price_3=self._safe_float(row.get('bid_price_3')),
                        bid_volume_3=self._safe_int(row.get('bid_volume_3')),
                        ask_price_1=self._safe_float(row.get('ask_price_1')),
                        ask_volume_1=self._safe_int(row.get('ask_volume_1')),
                        ask_price_2=self._safe_float(row.get('ask_price_2')),
                        ask_volume_2=self._safe_int(row.get('ask_volume_2')),
                        ask_price_3=self._safe_float(row.get('ask_price_3')),
                        ask_volume_3=self._safe_int(row.get('ask_volume_3')),
                        mid_price=self._safe_float(row.get('mid_price')),
                    )
                    prices.append(level)
        
        # Sort by day, timestamp, then product
        prices.sort(key=lambda x: (x.day, x.timestamp, x.product))
        return prices
    
    def load_trades(self) -> list[Trade]:
        """Load all trade data from CSV files"""
        trades = []

        # Find all trade files
        trade_files = glob.glob(self.data_dir + "/trades_*.csv")

        for filepath in sorted(trade_files):
            with open(filepath, 'r') as f:
                reader = csv.DictReader(f, delimiter=';')
                for row in reader:
                    if row.get('symbol'):  # Skip empty rows
                        trade = Trade(
                            timestamp=int(row['timestamp']),
                            buyer=row.get('buyer', ''),
                            seller=row.get('seller', ''),
                            symbol=row['symbol'],
                            price=float(row['price']),
                            quantity=int(row['quantity']),
                        )
                        trades.append(trade)
        
        trades.sort(key=lambda x: x.timestamp)
        return trades
    
    @staticmethod
    def _safe_float(val) -> Optional[float]:
        if val and val.strip():
            return float(val)
        return None
    
    @staticmethod
    def _safe_int(val) -> Optional[int]:
        if val and val.strip():
            return int(val)
        return None


# ============================================================
# Strategy Components
# ============================================================
class FairValueEstimator:
    """Estimates fair value using rolling median and mean reversion"""
    
    def __init__(self, window: int = 20):
        self.window = window
        self.mid_prices: deque = deque(maxlen=window)
        self.fair_value: Optional[float] = None
    
    def update(self, mid_price: float) -> float:
        """Update fair value estimate with new mid price"""
        self.mid_prices.append(mid_price)
        if len(self.mid_prices) >= 5:
            # Use median for robustness to outliers
            sorted_prices = sorted(self.mid_prices)
            n = len(sorted_prices)
            if n % 2 == 0:
                self.fair_value = (sorted_prices[n//2 - 1] + sorted_prices[n//2]) / 2
            else:
                self.fair_value = sorted_prices[n//2]
        return self.fair_value or mid_price
    
    def get_mean_reversion_signal(self) -> float:
        """
        Returns signal strength for mean reversion.
        Positive = current price below fair value (buy signal)
        Negative = current price above fair value (sell signal)
        """
        if not self.mid_prices or self.fair_value is None:
            return 0.0
        
        current = self.mid_prices[-1]
        deviation = (self.fair_value - current) / self.fair_value
        return deviation


class VolatilityEstimator:
    """Estimates recent price volatility"""
    
    def __init__(self, window: int = 10):
        self.window = window
        self.returns: deque = deque(maxlen=window)
        self.last_price: Optional[float] = None
    
    def update(self, price: float) -> float:
        """Update volatility estimate"""
        if self.last_price is not None and self.last_price > 0:
            ret = abs(price - self.last_price) / self.last_price
            self.returns.append(ret)
        self.last_price = price
        
        if len(self.returns) < 2:
            return 0.001  # Default low volatility
        
        # Average absolute return
        return sum(self.returns) / len(self.returns)


class InventoryManager:
    """Manages positions and applies inventory-based risk controls"""
    
    def __init__(self, max_position: int):
        self.position = Position(quantity=0, symbol="")
        self.max_position = max_position
        self.trades: list[Trade] = []
    
    def update_position(self, trade: Trade):
        """Update position when a trade executes"""
        qty = trade.quantity
        if trade.seller == "SUBMISSION":  # We sold
            self.position.quantity -= qty
            if self.position.quantity < 0:
                # Update avg entry for short
                prev_qty = abs(self.position.quantity) - qty
                if prev_qty > 0:
                    self.position.avg_entry_price = (
                        (self.position.avg_entry_price * prev_qty + trade.price * qty) / 
                        abs(self.position.quantity)
                    )
                else:
                    self.position.avg_entry_price = trade.price
        elif trade.buyer == "SUBMISSION":  # We bought
            self.position.quantity += qty
            if self.position.quantity > 0:
                # Update avg entry for long
                prev_qty = abs(self.position.quantity) - qty
                if prev_qty > 0:
                    self.position.avg_entry_price = (
                        (self.position.avg_entry_price * prev_qty + trade.price * qty) / 
                        self.position.quantity
                    )
                else:
                    self.position.avg_entry_price = trade.price
        
        self.trades.append(trade)
    
    def get_inventory_skew(self) -> float:
        """
        Returns skew factor based on current inventory.
        Positive = we're long, should lower bids/asks to reduce position
        Negative = we're short, should raise bids/asks to reduce position
        """
        if self.max_position == 0:
            return 0.0
        return self.position.quantity / self.max_position
    
    def can_buy(self, quantity: int) -> bool:
        return self.position.quantity + quantity <= self.max_position
    
    def can_sell(self, quantity: int) -> bool:
        return self.position.quantity - quantity >= -self.max_position


# ============================================================
# Main Strategy
# ============================================================
class MarketMakingStrategy:
    """
    Mean-Reversion Market Making Strategy v1.0
    
    This strategy:
    1. Estimates fair value using rolling median
    2. Places bid/ask orders around fair value
    3. Skews quotes based on inventory
    4. Widens spread during high volatility
    """
    
    def __init__(self, config: Config):
        self.config = config
        
        # Per-product state
        self.fair_value_estimators = {
            "EMERALDS": FairValueEstimator(config.MA_WINDOW),
            "TOMATOES": FairValueEstimator(config.MA_WINDOW),
        }
        self.volatility_estimators = {
            "EMERALDS": VolatilityEstimator(config.VOL_LOOKBACK),
            "TOMATOES": VolatilityEstimator(config.VOL_LOOKBACK),
        }
        self.inventory_managers = {
            "EMERALDS": InventoryManager(config.EMERALDS_MAX_POSITION),
            "TOMATOES": InventoryManager(config.TOMATOES_MAX_POSITION),
        }
        
        # Trading log
        self.signals: list[Signal] = []
        self.order_log: list[dict] = []
    
    def process_orderbook(self, book: OrderBookLevel) -> Optional[Signal]:
        """Process a single order book snapshot and generate trading signal"""
        product = book.product
        
        if product not in self.fair_value_estimators:
            return None
        
        # Update estimators
        mid_price = book.mid_price or ((book.bid_price_1 + book.ask_price_1) / 2 if book.bid_price_1 and book.ask_price_1 else None)
        if mid_price is None:
            return None
        
        fair_value = self.fair_value_estimators[product].update(mid_price)
        volatility = self.volatility_estimators[product].update(mid_price)
        inventory_skew = self.inventory_managers[product].get_inventory_skew()
        
        # Get product-specific config
        if product == "EMERALDS":
            base_spread = self.config.EMERALDS_SPREAD_TARGET
            order_size = self.config.EMERALDS_ORDER_SIZE
            fair_value_default = self.config.EMERALDS_FAIR_VALUE
        else:  # TOMATOES
            base_spread = self.config.TOMATOES_SPREAD_TARGET
            order_size = self.config.TOMATOES_ORDER_SIZE
            fair_value_default = self.config.TOMATOES_FAIR_VALUE
        
        # Use default fair value if estimator hasn't converged
        if fair_value is None:
            fair_value = fair_value_default
        
        # Adjust spread based on volatility
        vol_adjustment = 1.0 + (volatility * self.config.VOL_SPREAD_MULTIPLIER * 100)
        adjusted_spread = base_spread * vol_adjustment
        
        # Calculate optimal bid/ask with inventory skew
        # If we're long (positive inventory), lower our quotes to sell
        # If we're short (negative inventory), raise our quotes to buy
        skew_adjustment = inventory_skew * self.config.INVENTORY_SKEW_FACTOR * adjusted_spread
        
        optimal_bid = fair_value - adjusted_spread + skew_adjustment
        optimal_ask = fair_value + adjusted_spread + skew_adjustment
        
        # Ensure we maintain minimum spread
        if optimal_ask - optimal_bid < 2:
            midpoint = (optimal_bid + optimal_ask) / 2
            optimal_bid = midpoint - 1
            optimal_ask = midpoint + 1
        
        # Determine action based on current market vs our quotes
        current_bid = book.bid_price_1
        current_ask = book.ask_price_1
        
        if current_bid is None or current_ask is None:
            return None
        
        # Check if we should place/update orders
        signal = self._generate_signal(
            product=product,
            optimal_bid=optimal_bid,
            optimal_ask=optimal_ask,
            current_bid=current_bid,
            current_ask=current_ask,
            order_size=order_size,
        )
        
        # Log the decision
        self.order_log.append({
            "timestamp": book.timestamp,
            "product": product,
            "fair_value": round(fair_value, 2),
            "mid_price": round(mid_price, 2),
            "volatility": round(volatility, 6),
            "inventory_skew": round(inventory_skew, 4),
            "optimal_bid": round(optimal_bid, 2),
            "optimal_ask": round(optimal_ask, 2),
            "current_bid": round(current_bid, 2),
            "current_ask": round(current_ask, 2),
            "signal": signal.action if signal else "HOLD",
            "signal_price": round(signal.price, 2) if signal else 0,
        })
        
        return signal
    
    def _generate_signal(
        self,
        product: str,
        optimal_bid: float,
        optimal_ask: float,
        current_bid: float,
        current_ask: float,
        order_size: int,
    ) -> Optional[Signal]:
        """Generate trading signal based on optimal vs current prices"""
        manager = self.inventory_managers[product]
        
        # Mean reversion signal strength
        fair_value = (optimal_bid + optimal_ask) / 2
        mid_price = (current_bid + current_ask) / 2
        mean_rev_strength = abs(fair_value - mid_price) / fair_value
        
        # Only trade if deviation is significant
        if mean_rev_strength < 0.0005:  # 0.05% threshold
            return None
        
        if fair_value > mid_price and manager.can_buy(order_size):
            # Price below fair value - BUY signal
            # Place bid at optimal price
            return Signal(
                symbol=product,
                action="BUY",
                price=round(optimal_bid, 2),
                quantity=order_size,
                confidence=min(mean_rev_strength * 100, 1.0),
            )
        elif fair_value < mid_price and manager.can_sell(order_size):
            # Price above fair value - SELL signal
            # Place ask at optimal price
            return Signal(
                symbol=product,
                action="SELL",
                price=round(optimal_ask, 2),
                quantity=order_size,
                confidence=min(mean_rev_strength * 100, 1.0),
            )
        
        return None
    
    def process_trade(self, trade: Trade):
        """Process an executed trade and update positions"""
        if trade.symbol in self.inventory_managers:
            self.inventory_managers[trade.symbol].update_position(trade)
    
    def get_summary(self) -> dict:
        """Get strategy performance summary"""
        summary = {
            "total_signals": len([s for s in self.signals if s]),
            "buy_signals": len([s for s in self.signals if s and s.action == "BUY"]),
            "sell_signals": len([s for s in self.signals if s and s.action == "SELL"]),
        }
        
        for product, manager in self.inventory_managers.items():
            summary[f"{product}_position"] = manager.position.quantity
            summary[f"{product}_trades"] = len(manager.trades)
        
        return summary


# ============================================================
# Backtesting Engine
# ============================================================
class Backtester:
    """Runs the strategy on historical data"""
    
    def __init__(self, strategy: MarketMakingStrategy):
        self.strategy = strategy
    
    def run(self, prices: list[OrderBookLevel], trades: list[Trade]) -> dict:
        """Run backtest on historical data"""
        trade_idx = 0
        signals_generated = 0
        
        for book in prices:
            # Process any trades that occurred at this timestamp
            while trade_idx < len(trades) and trades[trade_idx].timestamp <= book.timestamp:
                self.strategy.process_trade(trades[trade_idx])
                trade_idx += 1
            
            # Generate signal
            signal = self.strategy.process_orderbook(book)
            if signal:
                self.strategy.signals.append(signal)
                signals_generated += 1
        
        return self.strategy.get_summary()


# ============================================================
# Analysis Utilities
# ============================================================
def analyze_market_data(data_dir: str):
    """Analyze market data to understand patterns"""
    loader = DataLoader(data_dir)
    prices = loader.load_prices()
    trades = loader.load_trades()
    
    print("=" * 60)
    print("MARKET DATA ANALYSIS")
    print("=" * 60)
    
    # Analyze EMERALDS
    emerald_prices = [p for p in prices if p.product == "EMERALDS"]
    if emerald_prices:
        mids = [p.mid_price for p in emerald_prices if p.mid_price]
        spreads = [
            (p.ask_price_1 - p.bid_price_1) 
            for p in emerald_prices 
            if p.ask_price_1 and p.bid_price_1
        ]
        print(f"\nEMERALDS:")
        print(f"  Data points: {len(emerald_prices)}")
        print(f"  Mid price - Min: {min(mids):.2f}, Max: {max(mids):.2f}, Avg: {sum(mids)/len(mids):.2f}")
        print(f"  Spread - Min: {min(spreads):.2f}, Max: {max(spreads):.2f}, Avg: {sum(spreads)/len(spreads):.2f}")
    
    # Analyze TOMATOES
    tomato_prices = [p for p in prices if p.product == "TOMATOES"]
    if tomato_prices:
        mids = [p.mid_price for p in tomato_prices if p.mid_price]
        spreads = [
            (p.ask_price_1 - p.bid_price_1) 
            for p in tomato_prices 
            if p.ask_price_1 and p.bid_price_1
        ]
        print(f"\nTOMATOES:")
        print(f"  Data points: {len(tomato_prices)}")
        print(f"  Mid price - Min: {min(mids):.2f}, Max: {max(mids):.2f}, Avg: {sum(mids)/len(mids):.2f}")
        print(f"  Spread - Min: {min(spreads):.2f}, Max: {max(spreads):.2f}, Avg: {sum(spreads)/len(spreads):.2f}")
    
    # Analyze trades
    emerald_trades = [t for t in trades if t.symbol == "EMERALDS"]
    tomato_trades = [t for t in trades if t.symbol == "TOMATOES"]
    print(f"\nTRADE ACTIVITY:")
    print(f"  EMERALDS trades: {len(emerald_trades)}")
    print(f"  TOMATOES trades: {len(tomato_trades)}")
    
    return prices, trades


# ============================================================
# Main Execution
# ============================================================
def main():
    """Main entry point"""
    config = Config()
    
    # Step 1: Analyze market data
    print("Loading and analyzing market data...")
    prices, trades = analyze_market_data(config.DATA_DIR)
    
    # Step 2: Initialize strategy
    print("\n" + "=" * 60)
    print("INITIALIZING MARKET MAKING STRATEGY")
    print("=" * 60)
    
    strategy = MarketMakingStrategy(config)
    backtester = Backtester(strategy)
    
    # Step 3: Run backtest
    print("\nRunning backtest...")
    results = backtester.run(prices, trades)
    
    # Step 4: Print results
    print("\n" + "=" * 60)
    print("BACKTEST RESULTS")
    print("=" * 60)
    for key, value in results.items():
        print(f"  {key}: {value}")
    
    # Step 5: Sample signals
    print(f"\nSample trading signals (first 20):")
    for signal in strategy.signals[:20]:
        print(f"  [{signal.symbol}] {signal.action} @ {signal.price:.2f} x {signal.quantity} "
              f"(confidence: {signal.confidence:.2f})")
    
    # Step 6: Sample order log
    print(f"\nSample order book decisions (first 10):")
    for log in strategy.order_log[:10]:
        print(f"  T={log['timestamp']} | {log['product']} | FV={log['fair_value']:.2f} | "
              f"Bid: {log['optimal_bid']:.2f} | Ask: {log['optimal_ask']:.2f} | "
              f"Action: {log['signal']}")
    
    print("\n" + "=" * 60)
    print("Strategy ready for live trading!")
    print("=" * 60)
    
    return strategy


if __name__ == "__main__":
    strategy = main()
